### PR TITLE
Release 7.13

### PR DESCRIPTION
**Pull request by vbgl**
I have been waiting for this release to happen, but it is already there!

### CODE REVIEW

**Comment by chetmurthy** [comment]
Vincent, are you still using version 7.12/3 ?  Have you thought about upgrading to version 8.00 ?  If you have problems with doing so, I'm happy to help you to get it done, and to fix problems you encounter.  version 8.00 has a *ton* of new stuff, and full support for modern OCaml syntax including PPX syntax.

**Comment by vbgl** [comment]
Can you compile Coq 8.9 (and older versions) with campl5 8.0? This is the kind of problems I encounter.

**Comment by chetmurthy** [comment]
It's a good question.  I don't know the answer.  Have you tried?  I'd be happy to help you to make it work.

**Comment by vbgl** [comment]
Sorry, but I think there is a misunderstanding: I have no plan to work on this. I just want to be able to build legacy Coq versions. If new versions of camlp5 break legacy developments, then I’ll use old versions of camlp5.

**Comment by chetmurthy** [comment]
Ah, ok.  yeah, for legacy Coq versions, you might as well use legacy Camlp5.   I plan to maintain the 7.xx stream of versions until something truly breaking forces me to stop.  So I would hope you can continue to use those with newer versions of OCaml, to compile legacy Coq versions.

**Comment by vbgl** [comment]
Cool. Thanks.

**Pull request merged**
